### ISSUE TITLE
Set up documentation deployment

### ISSUE THREAD

**Issue by tmcw** [georust/rust-polyline#6]

**Comment by urschrei** [comment]
How extensive would you like the doc deployment to be? Setting up [travis-cargo](https://github.com/huonw/travis-cargo) is straightforward, but the more thorough approach would be to set up [rust-everywhere](https://github.com/japaric/rust-everywhere), which generates docs on push, and creates zipped, github-hosted binary releases for all major platforms when a tag is pushed.

**Comment by tmcw** [comment]
cc @frewsxcv - I set up most of the parts for rust-cargo in d7fbbb788acb0d30c8d55f8a2480b210304d5cde but can't get a token for push to this repository, could you run through https://www.hoverbear.org/2015/03/07/rust-travis-github-pages/#givingtravispermissions since you have admin to the georust organization?

**Comment by frewsxcv** [comment]
While it's not completely done, I think it's safe to link to https://beta.docs.rs/polyline/ for now, which should have documentation for whatever the latest published version is.

**Comment by frewsxcv** [comment]
I opened #9 which adds a link to the docs.rs generated documentation for rust-polyline. In my opinion, I think having docs.rs generate the documentation for this crate is more than sufficient.
